package set

var Set map[string]bool = map[string]bool{
	"IND":                   true,
	" ":                     true,
	"-":                     true,
	"_":                     true,
	"MARUTI SUZUKI":         true,
	"HYUNDAI":               true,
	"TATA MOTORS":           true,
	"MAHINDRA & MAHINDRA":   true,
	"TOYOTA":                true,
	"HONDA":                 true,
	"FORD":                  true,
	"RENAULT":               true,
	"NISSAN":                true,
	"VOLKSWAGEN":            true,
	"MERCEDES-BENZ":         true,
	"BMW":                   true,
	"AUDI":                  true,
	"SKODA":                 true,
	"VOLVO":                 true,
	"JEEP":                  true,
	"KIA":                   true,
	"MG MOTOR":              true,
	"JAGUAR LAND ROVER":     true,
	"FIAT":                  true,
	"LAMBORGHINI":           true,
	"PORSCHE":               true,
	"ROLLS-ROYCE":           true,
	"BENTLEY":               true,
	"ASTON MARTIN":          true,
	"FERRARI":               true,
	"MASERATI":              true,
	"ISUZU":                 true,
	"FORCE MOTORS":          true,
	"PREMIER":               true,
	"BAJAJ AUTO":            true,
	"TVS MOTORS":            true,
	"HERO MOTOCORP":         true,
	"ROYAL ENFIELD":         true,
	"MAHINDRA TWO WHEELERS": true,
	"YAMAHA":                true,
	"SUZUKI MOTORCYCLE":     true,
	"KAWASAKI":              true,
	"TRIUMPH MOTORCYCLES":   true,
	"HARLEY-DAVIDSON":       true,
	"HYOSUNG":               true,
	"INDIAN MOTORCYCLE":     true,
	"PIAGGIO":               true,
	"DUCATI":                true,
	"APRILIA":               true,
	"BENELLI":               true,
	"MV AGUSTA":             true,
	"NORTON":                true,
	"HUSQVARNA":             true,
	"BMW MOTORRAD":          true,
	"KTM":                   true,
	"JAWA":                  true,
	"KYMCO":                 true,
	"OLA ELECTRIC":          true,
}
